services:
  elasticsearch:
    build:
      context:  Elasticsearch/
      dockerfile: Dockerfile
    container_name: esn00
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9200 || exit 1"]
      interval: 10s
      retries: 5

  devcontainer:
    build:
      context:  .devcontainer/
      dockerfile: dockerfile
    container_name: dev-container
    volumes:
      - /home/david/Call-Log-Handler:/workspace:cached
    network_mode: service:elasticsearch
    command: sleep infinity
    depends_on:
      - elasticsearch  # Ensures Elasticsearch starts first

  kibana:
    build:
      context: Kibana/
      dockerfile: Dockerfile
    container_name: kibana
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

  kibana:
    image: docker.elastic.co/kibana/kibana:8.17.1
    container_name: kib00
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch

volumes:
  esdata:
